    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.commessa.Commessa', 'it.biscottificio.thip.base.commessa.YCommessa', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.commessa.CommessaTM', 'it.biscottificio.thip.base.commessa.YCommessaTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('Commessa', 'YCommessa', '1', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.datiTecnici.modpro.ModelloProduttivo', 'it.biscottificio.thip.datiTecnici.modpro.YModelloProduttivo', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.datiTecnici.modpro.ModelloProduttivoTM', 'it.biscottificio.thip.datiTecnici.modpro.YModelloProduttivoTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('ModelloProduttivo', 'YModelloProduttivo', '1', 'N');
