    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.datiTecnici.modpro.ModelloProduttivo', 'it.biscottificio.thip.datiTecnici.modpro.YModelloProduttivo', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.datiTecnici.modpro.ModelloProduttivoTM', 'it.biscottificio.thip.datiTecnici.modpro.YModelloProduttivoTM', '0', 'Y');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('ModelloProduttivo', 'YModelloProduttivo', '1', 'Y');
